import { contextBridge, ipcRenderer, type IpcRendererEvent } from "electron"
import type {
  AgentInfo,
  AuthInfo,
  ChatRef,
  CommandInfo,
  CommandInput,
  ConfigPatch,
  FileText,
  McpConfig,
  McpStatus,
  McpToolCallResult,
  McpToolDef,
  MessageWithParts,
  MimoApi,
  PathInfo,
  PermissionReply,
  ProjectInfo,
  PromptInput,
  ProvidersResponse,
  RegistryKind,
  ServerEvent,
  ServerStatus,
  SessionInfo,
  SessionInfoFull,
  SkillInfo,
  TaskInfo,
  FileDiff,
  Todo,
  WebAgentBounds,
  WebAgentEvent,
  WebAgentState,
} from "@shared/types"

const sub = <T>(channel: string, cb: (payload: T) => void): (() => void) => {
  const handler = (_e: IpcRendererEvent, payload: T) => cb(payload)
  ipcRenderer.on(channel, handler)
  return () => ipcRenderer.removeListener(channel, handler)
}

const api: MimoApi = {
  getServerStatus: () => ipcRenderer.invoke("get-server-status"),
  onServerStatus: (cb) => sub<ServerStatus>("server-status", cb),
  onServerEvent: (cb) => sub<ServerEvent>("server-event", cb),
  reconnectServer: (url, password) => ipcRenderer.invoke("reconnect-server", { url, password }) as Promise<ServerStatus>,

  listSessions: (directory) => ipcRenderer.invoke("list-sessions", directory) as Promise<SessionInfo[]>,
  listProjectSessions: (directory) => ipcRenderer.invoke("list-project-sessions", directory) as Promise<SessionInfoFull[]>,
  listProjects: () => ipcRenderer.invoke("list-projects") as Promise<ProjectInfo[]>,
  deleteSession: (sessionID, directory) => ipcRenderer.invoke("delete-session", sessionID, directory) as Promise<boolean>,
  updateProject: (projectID, patch) => ipcRenderer.invoke("update-project", projectID, patch) as Promise<ProjectInfo>,
  getSessionDiff: (sessionID, messageID) => ipcRenderer.invoke("get-session-diff", sessionID, messageID) as Promise<FileDiff[]>,
  createSession: (opts) => ipcRenderer.invoke("create-session", opts) as Promise<SessionInfo>,
  updateSession: (sessionID, title, directory) => ipcRenderer.invoke("update-session", sessionID, title, directory) as Promise<SessionInfo>,
  getMessages: (sessionID, directory) => ipcRenderer.invoke("get-messages", sessionID, directory) as Promise<MessageWithParts[]>,
  getSubagentMessages: (sessionID, agentID, directory) => ipcRenderer.invoke("get-subagent-messages", sessionID, agentID, directory) as Promise<MessageWithParts[]>,
  prompt: (input: PromptInput) => ipcRenderer.invoke("prompt", input) as Promise<void>,
  sendCommand: (input: CommandInput) => ipcRenderer.invoke("send-command", input) as Promise<void>,
  abort: (sessionID, directory) => ipcRenderer.invoke("abort", sessionID, directory) as Promise<void>,
  summarizeSession: (sessionID, providerID, modelID, directory) =>
    ipcRenderer.invoke("summarize-session", sessionID, providerID, modelID, directory) as Promise<boolean>,
  deleteMessage: (sessionID, messageID, directory) => ipcRenderer.invoke("delete-message", sessionID, messageID, directory) as Promise<void>,
  replyPermission: (requestID, reply: PermissionReply, directory) =>
    ipcRenderer.invoke("reply-permission", requestID, reply, directory) as Promise<void>,
  questionReply: (requestID, answers: string[][], directory) =>
    ipcRenderer.invoke("question-reply", requestID, answers, directory) as Promise<void>,
  questionReject: (requestID, directory) =>
    ipcRenderer.invoke("question-reject", requestID, directory) as Promise<void>,
  updateSessionPermission: (sessionID, permission, directory) =>
    ipcRenderer.invoke("session-permission", sessionID, permission, directory) as Promise<void>,
  listPermissions: (directory) => ipcRenderer.invoke("list-permissions", directory) as Promise<import("@shared/types").Permission[]>,
  listQuestions: (directory) => ipcRenderer.invoke("list-questions", directory) as Promise<import("@shared/types").QuestionInfo[]>,
  getProviders: (directory) => ipcRenderer.invoke("get-providers", directory) as Promise<ProvidersResponse>,
  getAgents: (directory) => ipcRenderer.invoke("get-agents", directory) as Promise<AgentInfo[]>,
  getCommands: (directory) => ipcRenderer.invoke("get-commands", directory) as Promise<CommandInfo[]>,
  getSkills: (directory) => ipcRenderer.invoke("get-skills", directory) as Promise<SkillInfo[]>,
  installSkill: (sourceDir: string) => ipcRenderer.invoke("install-skill", sourceDir) as Promise<SkillInfo>,
  installSkillFile: (filePath: string) => ipcRenderer.invoke("install-skill-file", filePath) as Promise<SkillInfo>,
  uninstallSkill: (name: string) => ipcRenderer.invoke("uninstall-skill", name) as Promise<void>,
  getPath: () => ipcRenderer.invoke("get-path") as Promise<PathInfo | null>,
  pickExecutable: () => ipcRenderer.invoke("pick-executable") as Promise<string | null>,
  launchApp: (appId: string, extraArgs?: string) =>
    ipcRenderer.invoke("launch-app", appId, extraArgs) as Promise<{ ok: boolean; pid?: number; error?: string }>,
  getTodos: (sessionID, directory) => ipcRenderer.invoke("get-todos", sessionID, directory) as Promise<Todo[]>,
  getTasks: (sessionID, directory) => ipcRenderer.invoke("get-tasks", sessionID, directory) as Promise<TaskInfo[]>,
  getSessionStatus: (directory) => ipcRenderer.invoke("get-session-status", directory) as Promise<Record<string, import("@shared/types").SessionStatusInfo>>,

  getConfig: (directory) => ipcRenderer.invoke("get-config", directory) as Promise<Record<string, unknown>>,
  updateConfig: (patch: ConfigPatch, directory) => ipcRenderer.invoke("update-config", patch, directory) as Promise<void>,
  updateGlobalConfig: (patch) => ipcRenderer.invoke("update-global-config", patch) as Promise<Record<string, unknown>>,
  setAuth: (providerID, info: AuthInfo) => ipcRenderer.invoke("set-auth", providerID, info) as Promise<void>,
  removeProvider: (providerID) => ipcRenderer.invoke("remove-provider", providerID) as Promise<boolean>,
  setGlobalProvider: (providerID, entry) => ipcRenderer.invoke("set-global-provider", providerID, entry) as Promise<boolean>,
  setCompactionThreshold: (tokens, auto) => ipcRenderer.invoke("set-compaction-threshold", tokens, auto) as Promise<boolean>,
  setCompactRedirectModel: (model: { providerID: string; modelID: string } | null) => ipcRenderer.invoke("set-compact-redirect-model", model) as Promise<boolean>,
  getSubagentModels: () => ipcRenderer.invoke("get-subagent-models") as Promise<Record<string, string | null>>,
  setSubagentModel: (agentName, model) => ipcRenderer.invoke("set-subagent-model", agentName, model) as Promise<boolean>,

  getMcpStatus: (directory) => ipcRenderer.invoke("mcp-status", directory) as Promise<Record<string, McpStatus>>,
  addMcp: (name: string, config: McpConfig, directory) => ipcRenderer.invoke("mcp-add", name, config, directory) as Promise<Record<string, McpStatus>>,
  connectMcp: (name: string, directory) => ipcRenderer.invoke("mcp-connect", name, directory) as Promise<boolean>,
  disconnectMcp: (name: string, directory) => ipcRenderer.invoke("mcp-disconnect", name, directory) as Promise<boolean>,
  authenticateMcp: (name: string, directory) => ipcRenderer.invoke("mcp-authenticate", name, directory) as Promise<McpStatus>,
  removeMcpAuth: (name: string, directory) => ipcRenderer.invoke("mcp-remove-auth", name, directory) as Promise<boolean>,
  listMcpTools: (server: string, directory) => ipcRenderer.invoke("mcp-list-tools", server, directory) as Promise<McpToolDef[]>,
  callMcpTool: (server: string, tool: string, args: Record<string, unknown>, directory) => ipcRenderer.invoke("mcp-call-tool", server, tool, args, directory) as Promise<McpToolCallResult>,

  createChatSandbox: () => ipcRenderer.invoke("chat-create-sandbox") as Promise<{ id: string; directory: string }>,
  ensureProjectMarker: (directory) => ipcRenderer.invoke("ensure-project-marker", directory) as Promise<void>,
  getRegistry: (kind: RegistryKind) => ipcRenderer.invoke("registry-get", kind) as Promise<ChatRef[]>,
  saveRegistry: (kind: RegistryKind, items: ChatRef[]) => ipcRenderer.invoke("registry-save", kind, items) as Promise<void>,
  openPath: (path) => ipcRenderer.invoke("open-path", path) as Promise<string>,
  showItemInFolder: (path) => ipcRenderer.invoke("show-item-in-folder", path) as Promise<void>,
  notify: (title, body) => ipcRenderer.invoke("notify", title, body) as Promise<void>,
  readFileText: (path) => ipcRenderer.invoke("read-file-text", path) as Promise<FileText>,
  listWorkspaceFiles: (directory, sinceMs) => ipcRenderer.invoke("list-workspace-files", directory, sinceMs) as Promise<string[]>,
  getPreviewUrl: (path) => ipcRenderer.invoke("preview-url", path) as Promise<string>,
  setUserName: (name) => ipcRenderer.invoke("set-user-name", name) as Promise<string>,
  setCustomPrompt: (content) => ipcRenderer.invoke("set-custom-prompt", content) as Promise<string>,
  deleteSandbox: (directory) => ipcRenderer.invoke("delete-sandbox", directory) as Promise<void>,

  pickDirectory: () => ipcRenderer.invoke("pick-directory") as Promise<string | null>,
  pickSkillFile: () => ipcRenderer.invoke("pick-skill-file") as Promise<string | null>,
  pickAttachments: () => ipcRenderer.invoke("pick-attachments") as Promise<import("@shared/types").PickedAttachment[]>,
  onMenu: (cb) => sub<string>("menu-command", cb),
  minimizeWindow: () => ipcRenderer.send("window-minimize"),
  maximizeWindow: () => ipcRenderer.send("window-maximize"),
  closeWindow: (quit?: boolean) => ipcRenderer.send("window-close", quit),

  getSetting: (key) => ipcRenderer.invoke("get-setting", key),
  setSetting: (key, value) => ipcRenderer.invoke("set-setting", key, value) as Promise<void>,
  getStartupSettings: () => ipcRenderer.invoke("get-startup-settings") as Promise<import("@shared/types").StartupSettings>,
  updateCheckNow: () => ipcRenderer.invoke("update-check-now") as Promise<string>,
  setStartupSettings: (patch) => ipcRenderer.invoke("set-startup-settings", patch) as Promise<import("@shared/types").StartupSettings>,
  gitPush: (opts: { directory: string; remote?: string; branch?: string; force?: boolean }) =>
    ipcRenderer.invoke("git-push", opts) as Promise<string>,
  getAppInfo: () => ipcRenderer.invoke("get-app-info") as Promise<import("@shared/types").AppInfo>,

  // scheduler
  getSchedulerRules: () => ipcRenderer.invoke("get-scheduler-rules") as Promise<import("@shared/types").SchedulerRule[]>,
  setSchedulerRules: (rules: import("@shared/types").SchedulerRule[]) =>
    ipcRenderer.invoke("set-scheduler-rules", rules) as Promise<boolean>,
  getSchedulerStats: () => ipcRenderer.invoke("get-scheduler-stats") as Promise<import("@shared/types").SchedulerStats | null>,
  getSchedulerHistory: () => ipcRenderer.invoke("get-scheduler-history") as Promise<import("@shared/types").ExecutionLogEntry[]>,
  getRunningProcesses: () => ipcRenderer.invoke("get-running-processes") as Promise<import("@shared/types").RunningProcess[]>,
  killProcess: (pid: number) => ipcRenderer.invoke("kill-process", pid) as Promise<boolean>,
  schedulerRunNow: (ruleId: string) => ipcRenderer.invoke("scheduler-run-now", ruleId) as Promise<boolean>,

  // PTY + interactive bash
  ptyCreateAndConnect: (req) => ipcRenderer.invoke("pty-create-and-connect", req) as Promise<import("@shared/types").PtyInfo>,
  ptyInput: (ptyId, data) => ipcRenderer.invoke("pty-input", ptyId, data) as Promise<boolean>,
  ptyResize: (ptyId, cols, rows) => ipcRenderer.invoke("pty-resize", ptyId, cols, rows) as Promise<boolean>,
  ptyAbort: (ptyId) => ipcRenderer.invoke("pty-abort", ptyId) as Promise<boolean>,
  ptyForceReply: (ptyId, exitCode) => ipcRenderer.invoke("pty-force-reply", ptyId, exitCode) as Promise<boolean>,
  bashInteractiveList: () => ipcRenderer.invoke("bash-interactive-list") as Promise<import("@shared/types").BashInteractiveRequest[]>,
  onPtyOutput: (cb) => sub<{ id: string; data: string }>("pty-output", cb),
  onPtyExit: (cb) => sub<{ id: string; exitCode: number }>("pty-exit", cb),

  // Web Agent
  webagentCreateSandbox: () => ipcRenderer.invoke("webagent-create-sandbox") as Promise<{ id: string; directory: string }>,
  webagentCreateView: (sessionId, url) => ipcRenderer.invoke("webagent:create-view", sessionId, url) as Promise<void>,
  webagentAttachView: (sessionId) => ipcRenderer.invoke("webagent:attach-view", sessionId) as Promise<void>,
  webagentDetachView: (sessionId) => ipcRenderer.invoke("webagent:detach-view", sessionId) as Promise<void>,
  webagentDestroyView: (sessionId) => ipcRenderer.invoke("webagent:destroy-view", sessionId) as Promise<void>,
  webagentSetBounds: (bounds: WebAgentBounds) => ipcRenderer.invoke("webagent:set-bounds", bounds) as Promise<void>,
  webagentSetHidden: (hidden: boolean) => ipcRenderer.invoke("webagent:set-hidden", hidden) as Promise<void>,
  webagentNavigate: (sessionId, url) => ipcRenderer.invoke("webagent:navigate", sessionId, url) as Promise<void>,
  webagentSetZoom: (sessionId, opts) => ipcRenderer.invoke("webagent:set-zoom", sessionId, opts) as Promise<number>,
  webagentGetZoom: (sessionId) => ipcRenderer.invoke("webagent:get-zoom", sessionId) as Promise<number>,
  webagentGetState: (sessionId) => ipcRenderer.invoke("webagent:get-state", sessionId) as Promise<WebAgentState>,
  webagentSessionSetUrl: (sandboxId, url) => ipcRenderer.invoke("webagent:set-session-url", sandboxId, url) as Promise<void>,
  onWebagentEvent: (cb) => sub<WebAgentEvent>("webagent:event", cb),
}

contextBridge.exposeInMainWorld("mimo", api)
